FROM golang:1.18.5 AS builder

RUN apt update -y --no-install-recommends && \
    apt install -y --no-install-recommends make git curl procps zip libucl-dev zlib1g-dev pkg-config libczmq-dev build-essential debhelper jq zip

RUN curl --silent --show-error -kfL -o upx.tar.xz "https://github.com/upx/upx/releases/download/v3.96/upx-3.96-src.tar.xz" && \
    mkdir -p /usr/local/upx && \
    tar -xf upx.tar.xz -C /usr/local/upx --strip-components 1 && \
    cd /usr/local/upx && \
    make all && \
    ln -s /usr/local/upx/src/upx.out /usr/bin/upx

WORKDIR /go

ENV VSN=1.7.4
RUN curl --silent --show-error -kfL -o ekuiper.tar.gz "https://github.com/lf-edge/ekuiper/archive/refs/tags/${VSN}.tar.gz" && \
    mkdir -p ekuiper && \
    tar -zxf ekuiper.tar.gz -C ekuiper --strip-components 1 && \
    cd ekuiper && \
    make build_with_edgex

FROM python:3.8.12-slim-bullseye

COPY --from=builder /go/ekuiper/_build/kuiper-* /kuiper/
COPY --from=builder /go/ekuiper/sdk/python /sdk/python
COPY docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

RUN apt-get update --no-install-recommends && \
    apt-get install -y --no-install-recommends pkg-config libczmq-dev wget cmake libffi-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /sdk/python
RUN python3 setup.py sdist && python3 setup.py install

ENV KUIPER_HOME="/kuiper" \
    KUIPER__BASIC__CONSOLELOG=true

WORKDIR ${KUIPER_HOME}

EXPOSE 9081 20498

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

CMD ["./bin/kuiperd"]
