name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
        suffix:
          - ""
          - "-slim"
          - "-slim-python"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
            suffix=${{ matrix.suffix }}
          tags: type=raw,value=${{ matrix.version }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.version }}/Dockerfile${{ matrix.suffix }}
          context: ${{ matrix.version }}
      - run: docker run -d --name ekuiper ghcr.io/${{ github.repository }}:${{ matrix.version }}${{ matrix.suffix }}
      - name: Check docker container
        timeout-minutes: 1
        run: |
          ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ekuiper)
          sleep 5
          if ! curl ${ip_address}:9081  >/dev/null 2>&1; then
              echo "docker image failed"
              docker logs ekuiper
              exit 1
          fi
